### ISSUE TITLE
A Cluster should not allow deletion while it is deployed

### ISSUE THREAD

**Issue by mbfm** [eclipse-opendut/opendut#116]
It should not be possible to delete a cluster, when it is still deployed. The user should get feedback about this.

Currently, it looks like this in LEA:
![Screenshot_20240227_125659](https://github.com/eclipse-opendut/opendut/assets/148466978/9faad8f9-2b33-44f8-bc80-1a1ecbc5948a)

Tasks:
- [ ] Implement in CLEO.
- [ ] Implement in LEA.

**Comment by mirenz1** [comment]
Deactivate delete button in case cluster is deployed
