### ISSUE TITLE
Provide documentation as GitHub Page (proper)

### ISSUE THREAD

**Issue by mbfm** [eclipse-opendut/opendut#118]
Follow-up story to #89.

Tasks:
- [x] Move code from https://github.com/eclipse-opendut/eclipse-opendut.github.io (excluding the `book/` folder) into this repo into folder `opendut-homepage`.
- [x] Create `cargo ci doc homepage build` command, which builds the book first and then places everything into `target/ci/homepage`.
- [x] Add GitHub workflow which calls `cargo ci doc homepage build` and pushes artifact to eclipse-opendut.github.io repo.

Preparation for #126.

**Comment by reimarstier** [comment]
Can this be closed as it is already marked as done? @mbfm @mtwardawski
