### ISSUE TITLE
EDGAR should use the client id and secret provided in the setup-string

### ISSUE THREAD

**Issue by reimarstier** [eclipse-opendut/opendut#132]
Issue #112 introduced a new field `AuthConfig` in `opendut-types/src/util/net.rs`.
The PeerSetup struct is defined here: `opendut-types/src/peer/mod.rs`
The OIDC client_id and client_secret shall be used during setup.

EDGAR should:
- [x] Extract client id and secret from peer setup-string
- [x] Store client id and secret in EDGAR's configuration file
- [x] Enable OIDC in EDGAR's configuration file

**Comment by mtwardawski** [comment]
EDGAR should:

- [ ] Extract client id and secret from peer setup-string
- [ ] Store client id and secret in EDGAR's configuration file
- [ ] Enable OIDC in EDGAR's configuration file
