### ISSUE TITLE
Delete OIDC client once a peer gets deleted

### ISSUE THREAD

**Issue by reimarstier** [eclipse-opendut/opendut#149]
Issue #112 added client credentials to the peer setup string. These credentials are valid for the identity provider Keycloak. Once a peer gets deleted these client credentials shall be deleted in keycloak as well.

- [x] Store mapping ClientId → PeerId in CARL or in Keycloak, see #201 for Keycloak solution
- [x] When a peer gets deleted, delete client credentials in keycloak as well.

The OIDC client manager contains test code to do this: `opendut-carl/src/peer/oidc_client_manager.rs`

Is related to depends on  #201.

**Comment by mirenz1** [comment]
Check existing test deleting clientId in keycloak
