### ISSUE TITLE
Re-Setup of Peer fails

### ISSUE THREAD

**Issue by mbfm** [eclipse-opendut/opendut#167]
Currently, it is only possible to set up a peer once after its creation. This happens, because the state is not properly cleaned out from the NetBird Server.  
We need to remove the peer (which logs out EDGAR's NetBird Client) and then re-create it in the NetBird Server. This will also become relevant for restoring persisted state (#18).

As a user, this means that LEA gets stuck after clicking the "Generate"-button in the Peer Setup-tab:

![Image](https://github.com/eclipse-opendut/opendut/assets/148466978/d8a98289-26c0-4dfb-9efd-b71596b7425b)

Tasks:
- [ ] ~~Delete Peer from NetBird before it gets (re-)created, when the Generate-Button is clicked (or CLEO-equivalent happens).~~  
      ~~The `VpnManagementClient` already has an implementation for deleting a peer.~~
- [x] Test the EDGAR (re-)Setup.

**Comment by mirenz1** [comment]
- allow generating setup strings more than ones for the same peerID
- Netbird has to allow to reuse setup-keys for same peer
- CARL needs to check that there is only one per client trying to connect with the same peerID, first come first serve.
- netbird peer must not be deleted by CARL in Netbird when generating a new setup string

**Comment by mirenz1** [comment]
As it is now possible to theoretically use the same setup string on different peers to setup EDGAR, please add information, not to use the same setup string for different peers (LEA, CLEO, documentation)
