### ISSUE TITLE
Device is not removed from ClusterConfiguration, if respective Peer is deleted

### ISSUE THREAD

**Issue by mbfm** [eclipse-opendut/opendut#208]
Currently, it is possible to delete a Peer which has one of its devices included into a ClusterConfiguration.  
This means that deploying the cluster fails, because no respective Peer can be identified for the given device. This error is only visible in the CARL logs.

Tasks:
* [x] Test this to ensure that this is really what happens.
* [x] Block deleting peers which are included into a Cluster.
* [x] Block deleting devices which are included into a Cluster.
* [x] Offer the user a shortcut in LEA to remove a peer directly from a cluster, before it is deleted.  
  This is not allowed while the cluster is deployed.

**Comment by mirenz1** [comment]
Relates to #116

**Comment by mirenz1** [comment]
a peer can be assigned to different clusters, but deploying the cluster containing a peer already deployed in another cluster must not be allowed.
