### ISSUE TITLE
Cannelloni should be built with SCTP support

### ISSUE THREAD

**Issue by reimarstier** [eclipse-opendut/opendut#242]
- [x] Add SCTP support to cannelloni by including library in bundle and compiling with SCTP support
- [x] Update documentation:
  - [x] Installing SCTP is no longer required ([Readme](https://github.com/eclipse-opendut/cannelloni/blob/7ca9ff93a8f6fdba6f9c791480e3ccc5c6b49684/README.md?plain=1#L24))
  - [x] Check if licensing requirements are met (e.g. [Sources.md](https://github.com/eclipse-opendut/cannelloni/blob/7ca9ff93a8f6fdba6f9c791480e3ccc5c6b49684/Dockerfile#L40))
- [x] Check newly created binaries run on the following platforms (armv6, arm64, x64)
- [x] Check if newly created binaries work for our setup

The architecture armv7 is currently untested due to lack of hardware with soft-float installation (raspbian is hardfloat).
The binary `cangw` from the debian package can-utils is still required to run EDGAR.

**Comment by mirenz1** [comment]
Add cannelloni source code to cannelloni package

**Comment by reimarstier** [comment]
Added source code to cannelloni package. Tested the following packages on the hardware:
* cannelloni_linux-arm64-lts_1.1.0.tar.gz
* cannelloni_linux-armv6-lts_1.1.0.tar.gz
* cannelloni_manylinux_2_28-x64_1.1.0.tar.gz
