### ISSUE TITLE
Deep links in LEA do not work

### ISSUE THREAD

**Issue by reimarstier** [eclipse-opendut/opendut#45]
Howto reproduce: 
* Navigate to https://carl/, then press on clusters
* Refresh the page
* Or directly call: https://carl/clusters shows empty page

Technical background:
* On GRPC requests CARL handles API requests
* On HTTP requests CARL serves the distribution directory of LEA
* Currently the WASM file of LEA is only served on the root directory

**Comment by kKdH** [comment]
Yes, i noticed some broken routes in LEA already. I think this is related to the last update of the [leptos_router](https://crates.io/crates/leptos_router) crate. Version [0.5.5]( https://github.com/leptos-rs/leptos/releases/tag/v0.5.5) introduces a change to the behavior of the router for trailing slashes. Maybe this is the cause for the broken routes in LEA.
