### ISSUE TITLE
Error logging uses wrong module

### ISSUE THREAD

**Issue by mbfm** [eclipse-opendut/opendut#75]
The usage of the log statements [here](https://github.com/eclipse-opendut/opendut/blob/f085d7b6de1fc0fd24c10e52de438c3e6291bb60/opendut-util/src/logging.rs#L31-L61) leads to the logged module name being `opendut_util::logging` rather than the module name where the error was logged.

An example log statement:
```
[2024-02-06T14:01:15.087Z ERROR opendut_util::logging] Peer 'TestPeer' <20554d92-8e39-4331-83d3-ba71158360ce> could not be created, due to internal errors:
      An error occurred while creating peer <20554d92-8e39-4331-83d3-ba71158360ce>:
      Received status code indicating an error: HTTP status client error (405 Method Not Allowed) for url (https://netbird.opendut.local/api/groups)
```

This logging usage should either be implemented with a macro that captures the module name where the call happens or by using the newly stabilized [`inspect_err`](https://doc.rust-lang.org/stable/std/result/enum.Result.html#method.inspect_err) instead.

**Comment by kKdH** [comment]
PR #78 will close this issue.
